// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: books.sql

package database

import (
	"context"
)

const createBook = `-- name: CreateBook :one

INSERT INTO books (vendor_id, title, description, price, rate)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, vendor_id, title, description, price, rate, created_at, updated_at
`

type CreateBookParams struct {
	VendorID    int32
	Title       string
	Description string
	Price       string
	Rate        string
}

func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams) (Book, error) {
	row := q.db.QueryRowContext(ctx, createBook,
		arg.VendorID,
		arg.Title,
		arg.Description,
		arg.Price,
		arg.Rate,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.VendorID,
		&i.Title,
		&i.Description,
		&i.Price,
		&i.Rate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
