// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"
)

type Address struct {
	ID             int32
	UserID         int32
	Title          string
	PhoneNumber    string
	Governorate    string
	City           string
	AddressDetails string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type User struct {
	ID           int32
	Name         string
	Email        string
	PasswordHash string
	AvatarUrl    sql.NullString
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
