// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"context"
)

type Querier interface {
	AddBookAuthor(ctx context.Context, arg AddBookAuthorParams) error
	AddBookCategory(ctx context.Context, arg AddBookCategoryParams) error
	AddBookFavorite(ctx context.Context, arg AddBookFavoriteParams) error
	CountBooks(ctx context.Context) (int64, error)
	CreateAddress(ctx context.Context, arg CreateAddressParams) (Address, error)
	CreateApiToken(ctx context.Context, arg CreateApiTokenParams) (ApiToken, error)
	CreateAuthor(ctx context.Context, arg CreateAuthorParams) (Author, error)
	CreateBook(ctx context.Context, arg CreateBookParams) (Book, error)
	CreateCategory(ctx context.Context, name string) (Category, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVendor(ctx context.Context, arg CreateVendorParams) (Vendor, error)
	DeleteAddress(ctx context.Context, arg DeleteAddressParams) error
	GetAddresses(ctx context.Context, userID int32) ([]Address, error)
	GetApiToken(ctx context.Context, apiToken string) (ApiToken, error)
	GetBooks(ctx context.Context, arg GetBooksParams) ([]Book, error)
	GetBooksDetails(ctx context.Context, arg GetBooksDetailsParams) ([]GetBooksDetailsRow, error)
	GetCategoryByID(ctx context.Context, id int32) (Category, error)
	GetFavoriteBooks(ctx context.Context, userID int32) ([]GetFavoriteBooksRow, error)
	GetUser(ctx context.Context, id int32) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetVendors(ctx context.Context) ([]Vendor, error)
	RemoveBookFavorite(ctx context.Context, arg RemoveBookFavoriteParams) error
	UpdateAddress(ctx context.Context, arg UpdateAddressParams) (Address, error)
	UpdateUserImage(ctx context.Context, arg UpdateUserImageParams) error
}

var _ Querier = (*Queries)(nil)
