version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: mo_admin
      POSTGRES_PASSWORD: my_password
      POSTGRES_DB: bazar_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]

  app:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      DB_SOURCE: postgres://mo_admin:my_password@db:5432/bazar_db?sslmode=disable
      REDIS_ADDR: redis:6379

volumes:
  pgdata:
