-- +goose Up
-- +goose StatementBegin
CREATE TABLE vendors (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(250) UNIQUE NOT NULL,
  avatar_url TEXT NOT NULL,
  rate NUMERIC(2,1) CHECK (rate >= 1.0 AND rate <= 5.0) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE vendors;
-- +goose StatementEnd
