-- +goose Up
-- +goose StatementBegin
CREATE TABLE books
(
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendor_id   INT                                               NOT NULL REFERENCES vendors (id) ON DELETE CASCADE,
    title       VARCHAR(150)                                      NOT NULL,
    description TEXT                                              NOT NULL,
    price       DECIMAL                                           NOT NULL,
    rate        NUMERIC(2, 1) CHECK (rate >= 1.0 AND rate <= 5.0) NOT NULL,
    created_at  TIMESTAMP                                         NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMP                                         NOT NULL DEFAULT NOW()
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE books;
-- +goose StatementEnd
