-- +goose Up
-- +goose StatementBegin
CREATE TYPE author_type_enum AS ENUM (
    'Novelist',
    'Poet',
    'Essayist',
    'Biographer',
    'Historian',
    'Editor',
    'Translator',
    'Researcher',
    'Playwright',
    'Critic',
    'Columnist',
    'Journalist',
    'Screenwriter'
    );
CREATE TABLE authors
(
    id                INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              TEXT                                              NOT NULL,
    short_description VARCHAR(255)                                      NOT NULL,
    about             TEXT NOT NULL,
    avatar_url        TEXT,
    author_type       author_type_enum                                  NOT NULL,
    rate              NUMERIC(2, 1) CHECK (rate >= 1.0 AND rate <= 5.0) NOT NULL,
    created_at        TIMESTAMP                                         NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMP                                         NOT NULL DEFAULT NOW()
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE authors;
DROP TYPE author_type_enum;
-- +goose StatementEnd
